JobBatchName            = CMS_Singularity_$(Cluster)
executable = singularity_test.sh
universe   = vanilla
requirements = ( HasSingularity == true )
getenv     = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = job_$(Process).out
error = job_$(Process).err
log = job_$(Process).log

requirements = (Machine =?= "node2.intranet.local")
#transfer_input_files = singularity_test.sh
#transfer_output_files = hello/world.txt

+SingularityImage = "/shared/container_images/geant4_wCRIU.sif"
+SingularityBind = "/shared"
+SingularityExtraArgs= "--add-caps all"


notification = Error
notify_user = geonmo@kisti.re.kr

queue 1
