---
- name: 실습1 결과 설정 
  gather_facts: no
  serial: 5
  hosts: central_manager, submit, execute
  vars_files:
    - ../../ansible_setup/vars.yml
  tasks:
    - name: Yum clean all
      shell: 
        cmd: yum clean all
    - name: 방화벽 패키지를 설치합니다.
      package:
        name: firewalld
        state: present
    - name: 방화벽을 활성화합니다.
      service:
        name: firewalld
        state: started
    - name: HTCondor 패키지를 설치 여부를 확입합니다. 
      command: rpm -q condor      
      register: condor_installed
      ignore_errors: true
    - name: HTCondor 패키지를 설치합니다. 설치가 되어있다면 넘어갑니다. 
      shell: "curl -fsSL https://get.htcondor.org | /bin/bash -s -- --no-dry-run --{{ htcondor_role }} {{ central_manager }} --password {{ password }}"
      when: condor_installed.stdout.find('is not installed') != -1
    - name: Role 설정 내용이 정상인지 확인합니다.
      copy: 
        dest:  /etc/condor/config.d/01-{{ htcondor_role }}.config
        content: "CONDOR_HOST = {{ central_manager }}\n# For details, run condor_config_val use role:get_htcondor_{{ htcondor_role }}\nuse role:get_htcondor_{{ htcondor_role | replace('-','_')}}\n"
      notify:
        - restart htcondor
    - name: 도메인 정보를 설정합니다.
      copy: 
        dest: /etc/condor/config.d/02-domain.config
        content: "UID_DOMAIN={{ domain }}\nTRUST_UID_DOMAIN=true\nSOFT_UID_DOMAIN=true\n"
      notify:
        - restart htcondor
    - name: 동적 슬롯을 설정합니다.
      copy: 
        dest: /etc/condor/config.d/03-dynamic.config
        content: "NUM_SLOTS = 1\nNUM_SLOTS_TYPE_1 = 1\nSLOT_TYPE_1 = 100%\nSLOT_TYPE_1_PARTITIONABLE = TRUE\nCONSUMPTION_POLICY = true\n"
      notify:
        - restart htcondor
    - name: Apptainer 컨테이너 프로그램을 설치합니다.
      package:
        name: apptainer
        state: present
    - name: Apptainer 컨테이너 suid 프로그램을 설치합니다.
      package:
        name: apptainer-suid
        state: present
    - name: Apptainer 컨테이너 설정을 합니다.
      copy: 
        dest: /etc/condor/config.d/04-apptainer.config
        content: "SINGULARITY_JOB = !isUndefined(TARGET.SingularityImage)\nSINGULARITY_IMAGE_EXPR = TARGET.SingularityImage\nSINGULARITY_TARGET_DIR = /srv\nMOUNT_UNDER_SCRATCH = /tmp, /var/tmp\nSINGULARITY_BIND_EXPR=ifThenElse( isUndefined(TARGET.SingularityBind),\"/home\",TARGET.SingularityBind)\nSINGULARITY_EXTRA_ARGUMENTS=ifThenElse( isUndefined(TARGET.SingularityExtraArgs),\"\",TARGET.SingularityExtraArgs)\n"
      notify:
        - restart htcondor
  handlers:
    - name: restart htcondor
      service:
        name: condor
        state: restarted


        


