---
- name: Solution of Chapter1 
  gather_facts: no
  serial: 4
  hosts: all
  tasks:
    - name: Start firewalld service
      service:
        name: firewalld
        state: started
    - name: Check htcondor package 
      command: rpm -q condor
      register: condor_installed
      ignore_errors: true
    - name: Start htcondor installation procedure 
      shell: "curl -fsSL https://get.htcondor.org | /bin/bash -s -- --no-dry-run --{{ htcondor_role }} {{ central_manager }} --password {{ password }}"
      when: condor_installed.stdout.find('is not installed') != -1
    - name: Setup about domain information
      copy: 
        dest: /etc/condor/config.d/02-domain.config
        content: "UID_DOMAIN={{ domain }}\nTRUST_UID_DOMAIN=true\nSOFT_UID_DOMAIN=true\n"
      notify:
        - restart htcondor
    - name: Setup for dynamic slot
      copy: 
        dest: /etc/condor/config.d/03-dynamic.config
        content: "NUM_SLOTS = 1\nNUM_SLOTS_TYPE_1 = 1\nSLOT_TYPE_1 = 100%\nSLOT_TYPE_1_PARTITIONABLE = TRUE\nCONSUMPTION_POLICY = true\n"
      notify:
        - restart htcondor
    - name: Install Singularity
      package:
        name: singularity
        state: present
    - name: Setup for HTCondor singularity supporting
      copy: 
        dest: /etc/condor/config.d/04-singularity.config
        content: "SINGULARITY_JOB = !isUndefined(TARGET.SingularityImage)\nSINGULARITY_IMAGE_EXPR = TARGET.SingularityImage\nSINGULARITY_TARGET_DIR = /srv\nMOUNT_UNDER_SCRATCH = /tmp, /var/tmp\nSINGULARITY_BIND_EXPR=ifThenElse( isUndefined(TARGET.SingularityBind),\"/home\",TARGET.SingularityBind)\nSINGULARITY_EXTRA_ARGUMENTS=ifThenElse( isUndefined(TARGET.SingularityExtraArgs),\"\",TARGET.SingularityExtraArgs)\n"
      notify:
        - restart htcondor
  handlers:
    - name: restart htcondor
      service:
        name: condor
        state: restarted


        


