- name: Setup NFS packages
  gather_facts: no
  hosts: submit
  tasks:
    - name: Install nfs-utils
      package:
        name: nfs-utils
        state: latest
    - name: Create empty directory
      file:
        path: /shared
        owner: root
        group: root
        state: directory
        mode: "755" 
- name: Configure NFS server
  gather_facts: no
  hosts: submit
  tasks:
    - name: configure /etc/exports
      copy:
        dest: /etc/exports
        content: "/mnt/disk *(rw)\n"
      notify: restart nfs server
    - firewalld:
        service: nfs
        permanent: yes
        immediate: yes
        state: enabled
  handlers:
    - name: restart nfs server
      service:
        name: nfs-server
        state: restarted

- name: Configure nfs clients
  hosts: submit, execute
  gather_facts: no
  tasks:
    - name: make mountpoint
      mount:
        path: /shared
        src: node0.intranet.local:/mnt/disk
        fstype: nfs
        opts: "defaults,_netdev"
        state: mounted
